# Generated by Django 5.1.3 on 2025-01-16 20:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('same', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivamentosame',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arquivamentosame',
            name='data_arquivamento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='arquivamentosame',
            name='data_atendimento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='arquivamentosame',
            name='municipio',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arquivamentosame',
            name='num_caixa_arquivo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='arquivamentosame',
            name='num_ficha_atendimento',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='arquivamentosame',
            name='num_prontuario',
            field=models.CharField(default=datetime.date(2025, 1, 16), max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arquivamentosame',
            name='raca_cor',
            field=models.CharField(choices=[('', ''), ('BRANCA', 'BRANCA'), ('PRETA', 'PRETA'), ('PARDA', 'PARDA'), ('AMARELA', 'AMARELA'), ('INDIGENA', 'INDIGENA')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arquivamentosame',
            name='sexo',
            field=models.CharField(choices=[('', ''), ('MASCULINO', 'MASCULINO'), ('FEMININO', 'FEMININO')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arquivamentosame',
            name='tipo_prontuario',
            field=models.CharField(choices=[('', ''), ('PRONTUARIOS FATURADOS', 'PRONTUARIOS FATURADOS'), ('PRONTUARIOS NAO FATURADOS', 'PRONTUARIOS NAO FATURADOS'), ('PRONTUARIOS MATERNIDADE', 'PRONTUARIOS MATERNIDADE'), ('FICHAS', 'FICHAS'), ('NAO FATURADOS', 'NAO FATURADOS'), ('NAO IDENTIFICADOS', 'NAO IDENTIFICADOS'), ('OPME', 'OPME')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arquivamentosame',
            name='upload_prontuario',
            field=models.FileField(upload_to='Prontuario'),
        ),
    ]
