# Generated by Django 5.1.3 on 2025-01-22 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('same', '0002_alter_arquivamentosame_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivamentosame',
            name='data_arquivamento',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='arquivamentosame',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='arquivamentosame',
            name='nome_paciente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='arquivamentosame',
            name='num_ficha_atendimento',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='arquivamentosame',
            name='raca_cor',
            field=models.CharField(blank=True, choices=[('', ''), ('BRANCA', 'BRANCA'), ('PRETA', 'PRETA'), ('PARDA', 'PARDA'), ('AMARELA', 'AMARELA'), ('INDIGENA', 'INDIGENA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='arquivamentosame',
            name='sexo',
            field=models.CharField(blank=True, choices=[('', ''), ('MASCULINO', 'MASCULINO'), ('FEMININO', 'FEMININO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='arquivamentosame',
            name='tipo_prontuario',
            field=models.CharField(blank=True, choices=[('', ''), ('PRONTUARIOS FATURADOS', 'PRONTUARIOS FATURADOS'), ('PRONTUARIOS NAO FATURADOS', 'PRONTUARIOS NAO FATURADOS'), ('PRONTUARIOS MATERNIDADE', 'PRONTUARIOS MATERNIDADE'), ('FICHAS', 'FICHAS'), ('NAO FATURADOS', 'NAO FATURADOS'), ('NAO IDENTIFICADOS', 'NAO IDENTIFICADOS'), ('OPME', 'OPME')], max_length=100, null=True),
        ),
    ]
