# Generated by Django 5.1.3 on 2025-01-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('same', '0003_alter_arquivamentosame_data_arquivamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivamentosame',
            name='upload_prontuario',
            field=models.FileField(upload_to=models.CharField(max_length=100)),
        ),
    ]
